In [1]:
#Here I am importing all the necessary libraries I may need for analysis


import matplotlib.pyplot as plt
import numpy as np
import pandas as pd
import seaborn as sns
plt.style.use('fivethirtyeight')
%matplotlib inline
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LinearRegression

In [2]:
#Reading in of the dataset

brooklyn = pd.read_csv("brooklyn_sales_map.csv")

In [3]:
#What does the dataset look like

brooklyn.head(3)

,Unnamed: 0,borough,neighborhood,building_class_category,tax_class,block,lot,building_class,address,zip_code,...,XCoord,YCoord,ZoneMap,ZMCode,Sanborn,TaxMap,EDesigNum,Version,SHAPE_Leng,SHAPE_Area
0,1,3,DOWNTOWN-METROTECH,28 COMMERCIAL CONDOS,4,140,1001,R5,330 JAY STREET,11201,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,2,3,DOWNTOWN-FULTON FERRY,29 COMMERCIAL GARAGES,4,54,1,G7,85 JAY STREET,11201,...,988208.0,195011.0,12d,NaN,302 016,30101.0,NaN,17V1.1,1560.0,140132.0
2,3,3,BROOKLYN HEIGHTS,21 OFFICE BUILDINGS,4,204,1,O6,29 COLUMBIA HEIGHTS,11201,...,985952.0,195007.0,12d,NaN,302 004,30106.0,NaN,17V1.1,891.0,34656.0

In [4]:
#Getting rid of the first column since it's just added space

brooklyn = brooklyn.drop(brooklyn.columns[0], axis=1)

In [5]:
#What are the columns I am working with?

brooklyn.columns

Index(['borough', 'neighborhood', 'building_class_category', 'tax_class',
       'block', 'lot', 'building_class', 'address', 'zip_code',
       'residential_units', 'commercial_units', 'total_units', 'land_sqft',
       'gross_sqft', 'year_built', 'tax_class_at_sale',
       'building_class_at_sale', 'sale_price', 'year_of_sale', 'CD', 'CT2010',
       'CB2010', 'SchoolDist', 'Council', 'ZipCode', 'FireComp', 'PolicePrct',
       'HealthCent', 'HealthArea', 'SanitBoro', 'SanitDistr', 'SanitSub',
       'Address', 'ZoneDist1', 'SplitZone', 'BldgClass', 'LandUse',
       'Easements', 'OwnerType', 'OwnerName', 'LotArea', 'BldgArea', 'ComArea',
       'ResArea', 'AreaSource', 'NumBldgs', 'NumFloors', 'UnitsRes',
       'UnitsTotal', 'LotFront', 'LotDepth', 'BldgFront', 'BldgDepth',
       'ProxCode', 'IrrLotCode', 'LotType', 'BsmtCode', 'AssessLand',
       'AssessTot', 'ExemptLand', 'ExemptTot', 'YearBuilt', 'YearAlter1',
       'YearAlter2', 'BuiltFAR', 'ResidFAR', 'CommFAR', 'FacilFAR', 'BoroCode',
       'BBL', 'Tract2010', 'XCoord', 'YCoord', 'ZoneMap', 'ZMCode', 'Sanborn',
       'TaxMap', 'EDesigNum', 'Version', 'SHAPE_Leng', 'SHAPE_Area'],
      dtype='object')

In [6]:
#Setting up my rudimentary model
#In my head I thought that 'residential_units','commercial_units','land_sqft', and 'gross_sqft' would all be efficient 
#predictors of sales price


X = brooklyn.loc[:,['residential_units','commercial_units','land_sqft','gross_sqft']]
y = brooklyn.loc[:, 'sale_price']

In [7]:
#Here I am making sure I selected the right data

print(X)

        residential_units  commercial_units  land_sqft  gross_sqft
0                       0                 1        0.0         0.0
1                       0                 0   134988.0         0.0
2                       0                 0    32000.0    304650.0
3                       0               123   905000.0   2548000.0
4                       0                 1    20267.0    356000.0
5                       0                 0    57600.0         0.0
6                       0               102    12500.0    290440.0
7                     234                 3    50173.0    241764.0
8                       0                 0    44704.0         0.0
9                       0                 1   113800.0    547000.0
10                      0                 0    60400.0         0.0
11                      0                 0    62472.0         0.0
12                      8                 3    18175.0      5802.0
13                      0                 2    20704.0    253096.0
14                      0                 0        0.0         0.0
15                      0                 1    21175.0    363100.0
16                      0                 1    80000.0         0.0
17                    104                 0    20000.0     88797.0
18                      0                 0   278821.0         0.0
19                      0                 5    14800.0    223712.0
20                      0                 2   208426.0     95000.0
21                      0                 0        0.0         0.0
22                      0                 0    51680.0         0.0
23                      0                 3    12500.0    290440.0
24                     74                 0     7554.0     36750.0
25                    130                 0    42454.0    173476.0
26                      0                 3    21218.0    210488.0
27                     32                 0    26000.0     35200.0
28                      0                 2    20600.0    181576.0
29                      0                 3   138155.0     30000.0
...                   ...               ...        ...         ...
390851                  4                 1     2500.0      4500.0
390852                  4                 1     2462.0      4125.0
390853                  4                 2     2492.0      4125.0
390854                  4                 1     2250.0      4275.0
390855                  4                 1     2175.0      4500.0
390856                  4                 1     2158.0      4200.0
390857                  4                 1     2454.0      2100.0
390858                  4                 1     2500.0      4125.0
390859                  0                 1     1904.0      1905.0
390860                  0                 0        0.0         0.0
390861                  0                 0        0.0         0.0
390862                  0                 0        0.0         0.0
390863                  0                 1     7500.0     17550.0
390864                  0                 1    18700.0     18800.0
390865                  1                 1     5000.0      6200.0
390866                  0                 1     2500.0      2500.0
390867                  0                 1     2500.0      2500.0
390868                  0                 1     2500.0      5000.0
390869                  0                 1     4760.0      9000.0
390870                  0                 1        0.0         0.0
390871                  0                 1     4632.0     10880.0
390872                  0                 4      825.0       825.0
390873                  0                 0        0.0         0.0
390874                  0                 0        0.0         0.0
390875                  0                 0        0.0         0.0
390876                  0                 8     1600.0      1600.0
390877                  0                 0        0.0         0.0
390878                  3                 0     2300.0      3900.0
390879                  3                 0     2300.0      3900.0
390880                  0                 0     2765.0         0.0

[390881 rows x 4 columns]

In [8]:
#Once again just making sure I selected the right data

print(y)

0         499401179
1         345000000
2         340000000
3         276947000
4         202500000
5         185445000
6         171000000
7         169000000
8         165000000
9         161000000
10        160000000
11        158000000
12        154250000
13        138106368
14        135212000
15        135000000
16        132400000
17        125000000
18        124000000
19        121313223
20        120000000
21        117037454
22        112000000
23        107500000
24        105000000
25        103500000
26        102873750
27         98676252
28         98463962
29         95600000
            ...
390851            0
390852            0
390853            0
390854       560000
390855            0
390856            0
390857            0
390858       630000
390859        40000
390860            0
390861            0
390862            0
390863      3000000
390864            1
390865            0
390866            0
390867            0
390868       640000
390869       250000
390870       178193
390871            0
390872            0
390873            0
390874      2800000
390875            0
390876       153000
390877      1100000
390878       805000
390879       330000
390880       150000
Name: sale_price, Length: 390881, dtype: int64

In [9]:
#I am settting aside 25% of the data for testing the model

X_train, X_test, y_train, y_test = train_test_split(X, y, random_state=42)

In [10]:
#Here I am creating the model
lr = LinearRegression()

#Here I am asking the model to learn a function that predicts `y` from `X`
lr.fit(X_train, y_train)

LinearRegression(copy_X=True, fit_intercept=True, n_jobs=None,
         normalize=False)

In [11]:
#Here I am evaluating the model
#This is a terrible score. If the range is from 0 to 1, mine is way closer to 0. Essentiall saying I'm not predicting much

lr.score(X_test, y_test)

0.060065298037352166

In [12]:
#Here I am comparing the predictions to actual outcomes just to see how off I am

list(zip(lr.predict(X_test), y_test))

[(496122.13927899394, 0),
 (370967.2990422156, 997000),
 (370967.2990422156, 0),
 (426081.1164430868, 412500),
 (517330.8333663228, 0),
 (370967.2990422156, 294060),
 (595436.4218644747, 930000),
 (370967.2990422156, 1831831),
 (581564.948949516, 400000),
 (482561.78801547, 600000),
 (371552.8203804344, 224000),
 (412610.71134007035, 435000),
 (528541.8205893263, 0),
 (424774.306435537, 0),
 (427051.6464323461, 785000),
 (486054.0208710819, 0),
 (439140.64142873953, 335000),
 (370967.2990422156, 0),
 (370967.2990422156, 100000),
 (371552.8203804344, 90000),
 (658135.1430351783, 0),
 (370967.2990422156, 304212),
 (433902.0968012228, 420000),
 (371552.8203804344, 440000),
 (466622.32362139376, 35044),
 (422822.4101203515, 0),
 (486616.1775724035, 380000),
 (483286.950384352, 483000),
 (450624.08830838144, 924000),
 (370967.2990422156, 903166),
 (371552.8203804344, 355000),
 (1191878.717641035, 0),
 (564575.7457055087, 370000),
 (528652.6736486121, 0),
 (443334.9443872909, 280000),
 (507797.34092813043, 0),
 (560750.4346746819, 0),
 (370967.2990422156, 669000),
 (493449.76762536983, 600000),
 (461131.8484674905, 0),
 (371552.8203804344, 150000),
 (476565.1235086269, 0),
 (482310.06818943634, 0),
 (370967.2990422156, 481650),
 (492511.2313273258, 349000),
 (517355.1976826978, 0),
 (608082.102286368, 585000),
 (441491.2170436842, 625000),
 (423730.8356598786, 0),
 (371552.8203804344, 370000),
 (645186.1854120072, 925000),
 (472438.3741446411, 328948),
 (459440.25660929456, 750000),
 (371552.8203804344, 275000),
 (371552.8203804344, 250000),
 (536586.4824766328, 0),
 (494785.1638994578, 270000),
 (462464.4717887412, 0),
 (434911.27144324785, 530000),
 (481626.89936037007, 500000),
 (468078.2760332505, 0),
 (507312.8717284767, 0),
 (462464.4717887412, 0),
 (462382.7289726838, 0),
 (447406.5519570667, 0),
 (451048.00304924767, 0),
 (370348.3385808306, 390000),
 (470439.75800198095, 999000),
 (370967.2990422156, 800000),
 (500054.2111682829, 570000),
 (451838.2224497611, 0),
 (475617.72774310026, 610000),
 (462544.1107080232, 0),
 (477082.62645439786, 288000),
 (370967.2990422156, 390000),
 (370800.9347009087, 55000),
 (474881.26201888977, 0),
 (443756.207240533, 312580),
 (370967.2990422156, 480000),
 (370332.2267448408, 0),
 (658474.8557131196, 0),
 (511739.9707784067, 0),
 (458401.8718513989, 0),
 (648788.4744810585, 3450000),
 (508760.181715538, 10),
 (371552.8203804344, 82500),
 (435818.72249364306, 0),
 (370967.2990422156, 485706),
 (683427.2657818063, 825000),
 (530477.9250906045, 1572833),
 (474438.23724217864, 0),
 (481419.56670508644, 550000),
 (441110.32499263046, 0),
 (483809.45450170396, 0),
 (573709.5934451144, 0),
 (370967.2990422156, 2326501),
 (514815.3773554502, 740000),
 (370967.2990422156, 303186),
 (506773.5202622811, 534836),
 (440192.4385786641, 490000),
 (548968.3326812102, 0),
 (664538.9532765059, 575000),
 (371552.8203804344, 0),
 (370967.2990422156, 510000),
 (370967.2990422156, 314340),
 (423955.8289948984, 0),
 (371552.8203804344, 160000),
 (585844.421044209, 0),
 (487858.64871914516, 850000),
 (370967.2990422156, 334620),
 (2199261.2124981857, 0),
 (464881.45123661525, 765000),
 (506000.27676535706, 1100000),
 (370752.11095548497, 0),
 (370967.2990422156, 534581),
 (424986.25416576426, 0),
 (544611.9749808782, 0),
 (371552.8203804344, 875000),
 (594251.2214964579, 0),
 (371552.8203804344, 309270),
 (371552.8203804344, 1100000),
 (436095.38094327075, 750000),
 (460366.0743343655, 750000),
 (459812.087967822, 673000),
 (495511.0291303046, 0),
 (463925.03257719195, 0),
 (370967.2990422156, 0),
 (371552.8203804344, 140000),
 (425670.2890008113, 420000),
 (492080.8480493366, 390878),
 (579131.0372514054, 0),
 (426513.48412718833, 407300),
 (371552.8203804344, 610000),
 (371552.8203804344, 417500),
 (495171.5794690215, 999500),
 (428408.838071975, 0),
 (470636.5247531711, 185000),
 (1067630.2330581315, 3250000),
 (1088327.2647502865, 4000000),
 (904339.0736898361, 0),
 (370967.2990422156, 0),
 (481954.1957603855, 0),
 (522293.8135451806, 980000),
 (418411.90403933765, 0),
 (370967.2990422156, 999999),
 (370967.2990422156, 420810),
 (370967.2990422156, 325000),
 (370967.2990422156, 635000),
 (371552.8203804344, 255000),
 (413435.04251140845, 10),
 (370967.2990422156, 395460),
 (492657.10897596634, 0),
 (371552.8203804344, 0),
 (449266.71230594383, 741000),
 (442299.10616684286, 0),
 (370967.2990422156, 748413),
 (489426.1704701253, 470000),
 (447870.6499569423, 0),
 (430564.63328022306, 560000),
 (449506.83394491253, 998000),
 (514854.43635178916, 600000),
 (475664.07884495734, 595000),
 (506673.4264654111, 0),
 (370967.2990422156, 0),
 (370967.2990422156, 605858),
 (439644.39713133615, 592000),
 (442300.5708792056, 0),
 (370967.2990422156, 419500),
 (371552.8203804344, 235000),
 (441684.0232817711, 490000),
 (573121.4634664461, 930000),
 (447567.61058474437, 0),
 (1062601.4773392098, 0),
 (481337.7676747877, 0),
 (1071688.2483166025, 0),
 (459506.6671405735, 595000),
 (370967.2990422156, 845148),
 (419314.7168102199, 0),
 (580150.2769780078, 710000),
 (371552.8203804344, 1030000),
 (502621.0850183638, 0),
 (444196.23381738906, 0),
 (371552.8203804344, 0),
 (370967.2990422156, 0),
 (419879.047399214, 460000),
 (478162.6835828286, 439000),
 (370967.2990422156, 0),
 (462464.4717887412, 0),
 (502459.6415650272, 0),
 (469513.33958475146, 0),
 (371552.8203804344, 180000),
 (371552.8203804344, 0),
 (496879.3570570883, 0),
 (543768.4248581439, 488600),
 (442719.5647321015, 3515000),
 (371552.8203804344, 277000),
 (445513.88334197603, 3200000),
 (465594.8593315488, 0),
 (481966.3490216532, 0),
 (568840.8749100028, 0),
 (497500.73435397696, 0),
 (445016.309596492, 336000),
 (370967.2990422156, 0),
 (370967.2990422156, 555000),
 (587068.7433211557, 950000),
 (479424.3752817384, 0),
 (673460.0352212451, 203000),
 (402081.3948390938, 0),
 (462379.48151165247, 645000),
 (370967.2990422156, 385320),
 (370967.2990422156, 2350000),
 (435739.9967516741, 460000),
 (428540.79899109097, 245000),
 (440396.0335970811, 416500),
 (370967.2990422156, 0),
 (453590.1399331784, 750000),
 (370967.2990422156, 464000),
 (421241.9378772525, 145000),
 (447560.7084236365, 0),
 (432027.8090224682, 0),
 (487538.38104920683, 675000),
 (371552.8203804344, 327500),
 (687590.2739869496, 0),
 (506384.0647990643, 576800),
 (370967.2990422156, 0),
 (462464.4717887412, 0),
 (2712006.5554846316, 53000000),
 (489863.63122912205, 550000),
 (435714.61352280504, 0),
 (452929.44026450964, 0),
 (947824.1984739016, 0),
 (370967.2990422156, 738564),
 (556305.6941780319, 454000),
 (450126.32826170756, 550000),
 (426291.22169242485, 0),
 (434678.719494294, 551567),
 (451746.89058952325, 375000),
 (435006.50607014477, 0),
 (454934.28596801474, 0),
 (594253.5675710553, 0),
 (489639.71658621234, 0),
 (491421.61309303064, 800000),
 (371552.8203804344, 145000),
 (1067709.0248930617, 0),
 (453895.4605290017, 0),
 (370967.2990422156, 0),
 (451143.01793288277, 0),
 (470147.8041802307, 725000),
 (1493049.7371236214, 500000),
 (587256.2736749151, 0),
 (370574.88075959677, 0),
 (370967.2990422156, 825000),
 (452181.54655438266, 0),
 (519279.10131897585, 212500),
 (1446572.5161685073, 395000),
 (439165.62055153796, 0),
 (475568.5828283959, 930000),
 (20053303.9471599, 0),
 (542482.7391954703, 0),
 (371552.8203804344, 20080),
 (478587.16557378136, 675000),
 (370967.2990422156, 0),
 (497500.73435397696, 0),
 (421534.5167429288, 0),
 (437410.620736882, 690000),
 (481199.9864196488, 604200),
 (500061.57329091977, 1450000),
 (370967.2990422156, 945000),
 (370967.2990422156, 834965),
 (370967.2990422156, 0),
 (534110.7038338974, 495000),
 (413435.04251140845, 349800),
 (422748.8301283659, 255000),
 (371552.8203804344, 680000),
 (474310.1468422435, 465000),
 (657491.7927082896, 0),
 (505498.40911421005, 759000),
 (371552.8203804344, 519000),
 (416012.49051730894, 285000),
 (371552.8203804344, 86602),
 (370967.2990422156, 0),
 (438221.13541012054, 490000),
 (415445.5273211025, 0),
 (371552.8203804344, 108000),
 (415581.7455708347, 101095),
 (416636.9887062596, 0),
 (1023414.090816531, 0),
 (463115.0851540399, 0),
 (459382.70238353405, 459000),
 (678739.4911784881, 1250000),
 (455440.8657451603, 0),
 (371552.8203804344, 265000),
 (370165.2495354916, 0),
 (528825.6921318398, 0),
 (1660195.328644649, 0),
 (471863.65182425507, 0),
 (490611.1844895568, 559689),
 (473888.5203821352, 0),
 (699673.4820157749, 420000),
 (426549.18325518724, 500000),
 (422249.0856755796, 730000),
 (370967.2990422156, 281385),
 (445402.9641897292, 825000),
 (370967.2990422156, 0),
 (555480.491496957, 300000),
 (732430.4509168189, 75000),
 (437027.5862544512, 0),
 (482407.71568028384, 5000),
 (430897.7358546011, 228150),
 (371552.8203804344, 205000),
 (668708.6092628296, 1800000),
 (370332.2267448408, 0),
 (465498.7453281937, 284000),
 (370967.2990422156, 238290),
 (529288.9241257347, 0),
 (447865.36347632937, 0),
 (371552.8203804344, 590000),
 (371552.8203804344, 135000),
 (505240.651194668, 620000),
 (370967.2990422156, 425880),
 (540162.2094406752, 0),
 (449345.9789604552, 0),
 (371552.8203804344, 250000),
 (528569.3096745256, 2150000),
 (628027.1426820612, 1000000),
 (371552.8203804344, 70000),
 (517685.848832302, 0),
 (477692.1858209597, 0),
 (501665.1789955577, 930000),
 (440866.51014015725, 342000),
 (480455.85668393254, 0),
 (474882.55966307886, 580000),
 (481090.9939270702, 100),
 (1819970.2990267298, 4725000),
 (370967.2990422156, 0),
 (511553.02338977065, 155000),
 (370967.2990422156, 456300),
 (450411.24823462934, 525000),
 (455144.2949100854, 195000),
 (1068398.374704011, 2328000),
 (638755.3648738472, 0),
 (422313.4276693625, 0),
 (370967.2990422156, 565000),
 (445916.6862988544, 0),
 (477889.12987782614, 0),
 (441802.96373904496, 0),
 (487382.1659238608, 0),
 (371552.8203804344, 428000),
 (423503.36968129216, 37500),
 (539942.1145802392, 240000),
 (445704.2554499242, 335000),
 (448956.7868726795, 1175000),
 (466486.98360092146, 0),
 (437053.6998774227, 765000),
 (521089.8970098868, 1150000),
 (371552.8203804344, 700000),
 (370967.2990422156, 96330),
 (423927.5690163922, 315000),
 (1710474.8165853128, 0),
 (531388.8707826396, 460000),
 (555097.3882393966, 0),
 (366670.44583805994, 0),
 (432595.0831504526, 0),
 (371552.8203804344, 0),
 (371552.8203804344, 200000),
 (432419.8059043814, 0),
 (2305325.8094146987, 0),
 (370967.2990422156, 750000),
 (873449.1928239646, 3200000),
 (475764.2131410318, 0),
 (371552.8203804344, 310000),
 (370967.2990422156, 365040),
 (480068.49061822164, 35000),
 (537386.4929637751, 0),
 (478748.20492104744, 2946),
 (371552.8203804344, 464844),
 (495339.94749685243, 0),
 (370967.2990422156, 0),
 (456977.2719867898, 583000),
 (466354.8748466481, 0),
 (1692208.8743215236, 0),
 (458711.9026348397, 0),
 (460585.4175819062, 0),
 (538665.0677769863, 0),
 (371552.8203804344, 275000),
 (500151.6216212334, 695500),
 (443224.2564104022, 0),
 (481724.5468512176, 1200000),
 (371552.8203804344, 185900),
 (463863.7080636758, 430000),
 (472037.3924498592, 1070500),
 (628831.9774385189, 1700000),
 (531394.78742593, 2600000),
 (370967.2990422156, 570220),
 (593597.1837706299, 900000),
 (419509.0404357578, 0),
 (370967.2990422156, 0),
 (422022.16060953564, 552000),
 (443298.82505318, 248000),
 (416579.4537135153, 0),
 (370967.2990422156, 235000),
 (422983.32483702945, 494400),
 (616748.8381112062, 210000),
 (440183.2005804614, 0),
 (502360.30961855507, 0),
 (497228.31514914753, 799000),
 (462464.4717887412, 0),
 (426458.37108869903, 250000),
 (371552.8203804344, 998500),
 (681996.8636669924, 0),
 (370967.2990422156, 1252500),
 (553933.8798251254, 650000),
 (564487.7627323209, 425000),
 (370967.2990422156, 0),
 (462123.9772362028, 0),
 (601247.8058322838, 775000),
 (593960.7202111867, 1500000),
 (454547.06611046754, 0),
 (425227.56297999434, 960000),
 (501387.3474849337, 790000),
 (433396.1632867961, 0),
 (425250.043121682, 387553),
 (415543.17481194995, 418700),
 (420548.1960869603, 409000),
 (536003.159810254, 475000),
 (371552.8203804344, 490000),
 (535041.797417074, 18),
 (370967.2990422156, 750000),
 (461218.1296904187, 620000),
 (370967.2990422156, 395000),
 (585231.4581771278, 0),
 (542982.663251097, 0),
 (370967.2990422156, 448000),
 (514976.1321084824, 0),
 (433622.4684276653, 700000),
 (370967.2990422156, 940000),
 (486037.73172941577, 0),
 (371552.8203804344, 175000),
 (602828.88419768, 1000000),
 (520191.4732573413, 0),
 (513525.21497768135, 0),
 (522296.25473245175, 0),
 (462464.4717887412, 0),
 (737354.418102298, 810000),
 (370967.2990422156, 202800),
 (647214.5686831219, 840000),
 (716995.1078179821, 0),
 (469594.66453925625, 0),
 (370778.964015468, 242222),
 (1063403.4599222103, 500000),
 (371552.8203804344, 270000),
 (497824.38311104814, 412500),
 (418401.26816552086, 162000),
 (406109.94120562926, 3950),
 (371552.8203804344, 216500),
 (726074.6593417486, 0),
 (541897.2178572516, 0),
 (370967.2990422156, 376000),
 (371552.8203804344, 135000),
 (491637.7088795401, 625000),
 (371552.8203804344, 0),
 (797760.0149702237, 0),
 (430657.8339588942, 351000),
 (471420.1549101312, 418000),
 (466354.8748466481, 0),
 (463877.91058202786, 1000),
 (462464.4717887412, 0),
 (480915.0401091829, 0),
 (371552.8203804344, 235000),
 (1118562.3479755456, 1900000),
 (371552.8203804344, 0),
 (430250.91241625254, 0),
 (370967.2990422156, 990000),
 (651337.7674736246, 0),
 (370967.2990422156, 1380000),
 (458133.3412515683, 685000),
 (370967.2990422156, 0),
 (371552.8203804344, 0),
 (1212209.147702467, 0),
 (371552.8203804344, 695000),
 (371552.8203804344, 900000),
 (447090.4374621619, 0),
 (595426.2179876491, 0),
 (488729.11636782985, 0),
 (370185.75550856953, 398000),
 (482212.42069858883, 0),
 (419965.33175511693, 515000),
 (521855.9659747483, 1700000),
 (438880.34402888245, 280000),
 (626116.5728101843, 350000),
 (371552.8203804344, 400000),
 (426629.7899914733, 10),
 (593958.2790239154, 0),
 (483461.3918861443, 0),
 (529556.6189812864, 604200),
 (760034.7337443578, 2100000),
 (461229.495958338, 445000),
 (429048.4696362305, 0),
 (370967.2990422156, 280220),
 (370967.2990422156, 355000),
 (492367.52756635763, 225000),
 (370967.2990422156, 0),
 (371552.8203804344, 585000),
 (370967.2990422156, 712775),
 (532839.1172515588, 491000),
 (371552.8203804344, 250000),
 (370967.2990422156, 0),
 (371552.8203804344, 0),
 (371552.8203804344, 699000),
 (1117495.7720142733, 8500000),
 (680106.0890316915, 0),
 (370967.2990422156, 0),
 (371552.8203804344, 0),
 (371552.8203804344, 152000),
 (518684.2405565358, 0),
 (370771.64045365446, 970000),
 (453842.3216591222, 0),
 (370967.2990422156, 499000),
 (430492.76214302506, 125000),
 (443596.48675624887, 365000),
 (490311.89493010927, 590000),
 (370330.27379502385, 0),
 (490958.4459501077, 400000),
 (371552.8203804344, 285000),
 (787293.8394637178, 420000),
 (410981.58753847267, 0),
 (371552.8203804344, 400530),
 (541145.1914470964, 0),
 (370967.2990422156, 349830),
 (371552.8203804344, 96000),
 (444666.5118359961, 446800),
 (498953.35323503765, 910000),
 (439935.87489151594, 0),
 (460762.3317272651, 400000),
 (371552.8203804344, 0),
 (432581.20180138113, 560000),
 (515195.8389628892, 449000),
 (433593.63608032116, 0),
 (369599.8705634846, 3000000),
 (483435.41581343213, 125000),
 (370967.2990422156, 465000),
 (412918.8418487824, 1100000),
 (456879.6244959423, 595000),
 (410972.48833251843, 218000),
 (370332.2267448408, 462500),
 (569757.5038202017, 0),
 (416262.79830606806, 339999),
 (436990.12877694675, 0),
 (479590.86425363336, 1020000),
 (720963.6626482481, 1900000),
 (492284.64671097405, 0),
 (512391.518566033, 525000),
 (421217.96668565803, 520000),
 (370967.2990422156, 275000),
 (515940.7403357, 452335),
 (370967.2990422156, 0),
 (493522.5535194791, 410000),
 (461757.94817527576, 3475000),
 (371552.8203804344, 430000),
 (534046.7867799732, 1160000),
 (446584.6619729998, 0),
 (462464.4717887412, 110000),
 (370967.2990422156, 451230),
 (481761.2995283761, 760000),
 (612879.2850152225, 0),
 (581772.449867567, 10),
 (478836.03498772194, 900000),
 (452665.6288952055, 685000),
 (371552.8203804344, 84162),
 (430961.30695507705, 0),
 (447762.4295048689, 590000),
 (370820.4641990782, 0),
 (371552.8203804344, 348500),
 (371552.8203804344, 1950000),
 (408965.94793588616, 425390),
 (458499.5193422464, 590000),
 (487191.53199384804, 0),
 (370967.2990422156, 0),
 (409210.06666300487, 1),
 (608632.2829847027, 0),
 (500988.4959982495, 610000),
 (587909.769293607, 0),
 (370967.2990422156, 2555807),
 (371552.8203804344, 325000),
 (492348.6745926088, 0),
 (462387.2669733762, 0),
 (370967.2990422156, 0),
 (371552.8203804344, 165000),
 (452660.112433828, 1120000),
 (457609.71167695225, 0),
 (465992.0688001939, 0),
 (462464.4717887412, 0),
 (371552.8203804344, 225000),
 (464701.67450327944, 23000),
 (876801.5432622742, 0),
 (542715.2408138954, 295000),
 (963320.3899800564, 1450000),
 (453059.2587522486, 0),
 (505671.76486675977, 0),
 (370967.2990422156, 0),
 (433999.4545790851, 675000),
 (515195.8389628892, 30000),
 (513841.70724111266, 370000),
 (370967.2990422156, 0),
 (485450.74567883427, 0),
 (370967.2990422156, 290000),
 (454571.84159004554, 310000),
 (459694.747834789, 0),
 (467911.56219934236, 1250000),
 (371552.8203804344, 365000),
 (370967.2990422156, 0),
 (370967.2990422156, 728000),
 (570074.8373054462, 600000),
 (441449.5588348094, 0),
 (493391.7585568317, 494975),
 (371552.8203804344, 160000),
 (2407448.869357758, 0),
 (435173.5744680101, 520000),
 (493665.85516015324, 0),
 (557641.8031665826, 400000),
 (371552.8203804344, 571000),
 (496569.7142796767, 900000),
 (371552.8203804344, 365000),
 (518611.3941390229, 2600000),
 (494385.81786197453, 0),
 (479035.0676062836, 950000),
 (487451.6957202081, 720000),
 (371552.8203804344, 223000),
 (370967.2990422156, 316875),
 (503046.6276156086, 0),
 (533493.2693704723, 0),
 (439465.75489817344, 425000),
 (433945.16704737215, 0),
 (426003.9749253173, 0),
 (471437.8509703205, 700000),
 (466843.97830686625, 0),
 (371552.8203804344, 951000),
 (371552.8203804344, 325000),
 (434201.0966476852, 350000),
 (537774.4503199527, 770000),
 (415669.9534060358, 405000),
 (388152.5823228853, 0),
 (503046.6276156086, 0),
 (524797.3902927338, 0),
 (462464.4717887412, 0),
 (371552.8203804344, 47477),
 (462464.4717887412, 0),
 (567230.0140598981, 0),
 (370967.2990422156, 515000),
 (371552.8203804344, 375000),
 (481557.0601856213, 669000),
 (370332.2267448408, 150000),
 (370967.2990422156, 670000),
 (448229.83981674776, 556000),
 (470539.44451241015, 0),
 (371552.8203804344, 0),
 (370967.2990422156, 998500),
 (466722.40206200985, 795000),
 (494662.20707362227, 840000),
 (525659.5740047379, 425000),
 (613670.2670099214, 0),
 (411420.20207805414, 0),
 (452924.73007689224, 0),
 (370967.2990422156, 275000),
 (527003.8776798343, 0),
 (474337.37255200173, 0),
 (479353.52817578573, 730000),
 (370967.2990422156, 2030000),
 (462464.4717887412, 0),
 (541897.2178572516, 483000),
 (-11816573.291273989, 6500000),
 (436590.4415459837, 756234),
 (486949.6822670756, 0),
 (371552.8203804344, 363000),
 (442559.0996920545, 510000),
 (450398.5803983633, 875000),
 (445540.36057181377, 0),
 (462464.4717887412, 0),
 (608632.2829847027, 0),
 (709675.129490017, 0),
 (498186.94307669636, 0),
 (442202.9233883581, 510000),
 (503045.1629032459, 640500),
 (370967.2990422156, 0),
 (537064.4193879943, 0),
 (433162.18513890746, 0),
 (916850.9902775595, 0),
 (466089.1490409548, 0),
 (553500.9433375609, 0),
 (2067950.5454958638, 15800000),
 (457768.6876054736, 925000),
 (370967.2990422156, 0),
 (491446.4149101528, 0),
 (371552.8203804344, 439000),
 (823717.20228986, 1975000),
 (510467.6522485892, 620000),
 (370967.2990422156, 700000),
 (437358.75709780504, 0),
 (441936.6617888737, 615000),
 (544441.7031129438, 736667),
 (577629.1658846848, 650000),
 (371552.8203804344, 260000),
 (445807.5266907067, 475000),
 (432893.6737720931, 585000),
 (371552.8203804344, 214451),
 (422735.05412947084, 2572),
 (368575.6627301845, 170000),
 (429358.8357506122, 1210000),

In [13]:
#Now I am checking out how various X inputs correlate to my y output (sale_price)

brooklyn_regression = brooklyn.loc[:,['sale_price','residential_units','commercial_units','land_sqft','gross_sqft']]

In [14]:
brooklyn_regression.corr()

,sale_price,residential_units,commercial_units,land_sqft,gross_sqft
sale_price,1.000000,0.032021,0.098285,0.076056,0.265927
residential_units,0.032021,1.000000,0.003374,0.025103,0.140849
commercial_units,0.098285,0.003374,1.000000,0.042536,0.188725
land_sqft,0.076056,0.025103,0.042536,1.000000,0.287830
gross_sqft,0.265927,0.140849,0.188725,0.287830,1.000000

In [15]:
brooklyn_regression2 = brooklyn.loc[:,['sale_price','block','zip_code','SchoolDist','ZoneDist1']]

In [16]:
brooklyn_regression2.corr()

            sale_price     block  zip_code  SchoolDist
sale_price    1.000000 -0.062976 -0.005021   -0.053948
block        -0.062976  1.000000  0.011148    0.453755
zip_code     -0.005021  0.011148  1.000000    0.007082
SchoolDist   -0.053948  0.453755  0.007082    1.000000

In [17]:
brooklyn_regression3 = brooklyn.loc[:,['sale_price','LotArea','BldgArea','ComArea','ResArea']]

In [18]:
brooklyn_regression3.corr()

            sale_price   LotArea  BldgArea   ComArea   ResArea
sale_price    1.000000  0.056153  0.047476  0.238462  0.006780
LotArea       0.056153  1.000000  0.731811  0.271141  0.707354
BldgArea      0.047476  0.731811  1.000000  0.244988  0.986986
ComArea       0.238462  0.271141  0.244988  1.000000  0.087097
ResArea       0.006780  0.707354  0.986986  0.087097  1.000000

In [19]:
brooklyn_regression4 = brooklyn.loc[:,['sale_price','NumBldgs','NumFloors','UnitsRes','UnitsTotal']]

In [20]:
brooklyn_regression4.corr()

            sale_price  NumBldgs  NumFloors  UnitsRes  UnitsTotal
sale_price    1.000000  0.001720   0.050376  0.008932    0.012043
NumBldgs      0.001720  1.000000   0.116716  0.190281    0.190035
NumFloors     0.050376  0.116716   1.000000  0.752355    0.752987
UnitsRes      0.008932  0.190281   0.752355  1.000000    0.999616
UnitsTotal    0.012043  0.190035   0.752987  0.999616    1.000000

In [17]:
#Here I am testing a new model with different inputs than the first model.

testing = brooklyn.loc[:,['sale_price','ComArea','gross_sqft','NumFloors','UnitsTotal']].dropna()

In [18]:
X = testing.loc[:,['ComArea','gross_sqft','NumFloors','UnitsTotal']]
y = testing.loc[:, 'sale_price']

In [19]:
print(X)

          ComArea  gross_sqft  NumFloors  UnitsTotal
1             0.0         0.0        0.0         0.0
2        304650.0    304650.0       13.0         0.0
3       2548000.0   2548000.0        2.0       123.0
4         30000.0    356000.0       15.0         1.0
5         11200.0         0.0        0.0       525.0
6        290440.0    290440.0       37.0       102.0
7         27900.0    241764.0        6.0       237.0
8          4884.0         0.0       20.0       472.0
9        547000.0    547000.0        8.0         1.0
10            0.0         0.0        0.0         0.0
11            0.0         0.0        0.0         0.0
13       253096.0    253096.0       11.0         2.0
15        86353.0    363100.0       28.5         1.0
16       626140.0         0.0       10.0        32.0
17        17609.0     88797.0        7.0       104.0
18            0.0         0.0        0.0         0.0
19       223712.0    223712.0       12.0         5.0
20        52752.0     95000.0        6.0       142.0
22        76995.0         0.0       40.0       554.0
23       290440.0    290440.0       37.0       102.0
24            0.0     36750.0        7.0        74.0
25            0.0    173476.0        6.0       130.0
26       210488.0    210488.0        8.0         3.0
27            0.0     35200.0        3.0        32.0
28       181576.0    181576.0        8.0         2.0
29        30000.0     30000.0        1.0         3.0
30        58284.0    101358.0        1.0        52.0
31       292886.0    292886.0        1.0        32.0
33       232174.0    190750.0       10.0       355.0
35            0.0    104239.0       11.0         1.0
...           ...         ...        ...         ...
390843     1550.0      6200.0        3.0         6.0
390844     2548.0      5538.0        3.0         5.0
390845     1575.0      4725.0        3.0         5.0
390846     1425.0      4275.0        3.0         5.0
390847     1450.0      4350.0        3.0         5.0
390848     1431.0      4293.0        3.0         5.0
390849     1700.0      5100.0        3.0         8.0
390850     1500.0      4500.0        3.0         5.0
390851     1500.0      4500.0        3.0         5.0
390852     1375.0      4125.0        3.0         5.0
390853     1375.0      4125.0        3.0         6.0
390854     1425.0      4275.0        3.0         5.0
390855     1500.0      4500.0        3.0         5.0
390856     1400.0      4200.0        3.0         5.0
390857      700.0      2100.0        3.0         5.0
390858     1375.0      4125.0        3.0         5.0
390859     1905.0      1905.0        1.0         1.0
390863        0.0     17550.0        3.0        21.0
390864    18800.0     18800.0        1.0         1.0
390865     6300.0      6200.0        2.0         2.0
390866     2500.0      2500.0        1.0         1.0
390867     2500.0      2500.0        1.0         1.0
390868     3250.0      5000.0        2.0         3.0
390869     9000.0      9000.0        2.0         1.0
390871    10880.0     10880.0        6.0         1.0
390872      825.0       825.0        1.0         4.0
390876     1600.0      1600.0        1.0         8.0
390878        0.0      3900.0        3.0         3.0
390879        0.0      3900.0        3.0         3.0
390880        0.0         0.0        0.0         0.0

[303728 rows x 4 columns]

In [20]:
X_train, X_test, y_train, y_test = train_test_split(X, y, random_state=42)

# Create a model from that class
lr = LinearRegression()

# Ask the model to learn a function that predicts `y` from `X`
lr.fit(X_train, y_train)

LinearRegression(copy_X=True, fit_intercept=True, n_jobs=None,
         normalize=False)

In [21]:
#This score is even worse than the first model. I am definitely concerned. 

lr.score(X_test, y_test)

0.05535438704357676